language: php

sudo: required

notifications:
  email: false

services:
  - mysql

addons:
  postgresql: 9.6
  firefox: "47.0.1"
  #chrome: stable
  apt:
    packages:
      # can be omitted because mustache is not in use
      # - oracle-java8-installer
      # - oracle-java8-set-default
      - chromium-chromedriver
      - openjdk-8-jre-headless

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

# PHP Compatibility Matrix Moodle           End of life
# Moodle 3.5: php7.0, php7.1, php7.2 (exp)  10 May 2021
# Moodle 3.7: php7.1, php7.2, php7.3        9 November 2020
# Moodle 3.8: php7.1, php7.2, php7.3        10 May 2021
# Moodle 3.9: php7.2, php7.3, php7.4        ~ May 2023
# lim: limited, exp: expected, dev: non-production
# earlier versions of Moodle and php are not included, as support was dropped

php:
 - 7.2
 - 7.3
 - 7.4

env:
  global:
    # Set PROFILE to either chrome or firefox depending on your preference.
    - PROFILE=firefox
  matrix:
    - MOODLE_BRANCH=MOODLE_35_STABLE DB=pgsql
    - MOODLE_BRANCH=MOODLE_37_STABLE DB=pgsql
    - MOODLE_BRANCH=MOODLE_38_STABLE DB=pgsql
    - MOODLE_BRANCH=MOODLE_39_STABLE DB=pgsql

matrix:
  exclude:
    - php: 7.3
      env: MOODLE_BRANCH=MOODLE_35_STABLE DB=pgsql
    - php: 7.4
      env: MOODLE_BRANCH=MOODLE_37_STABLE DB=pgsql
    # technically MOODLE_38 has no offical PHP7.4 support, but allow that test for now
  include:
    # Technically PHP 7.1 is EOL, but MOODLE_35 is an LTS which has PHP 7.1 as the latest *non-conditional* supported version
    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_35_STABLE DB=pgsql
    # Some MySQL as backend with various PHP and Moodle versions, but just some to save matrix slots
    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_35_STABLE DB=mysqli
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_37_STABLE DB=mysqli
    - php: 7.3
      env: MOODLE_BRANCH=MOODLE_38_STABLE DB=mysqli
    - php: 7.4
      env: MOODLE_BRANCH=MOODLE_39_STABLE DB=mysqli
    # Some MariaDB as backend with various PHP versions, but just some to save matrix slots
    # TODO: Somehow behat doesn't run when mariadb is in use, all other stuff do
    # - php: 7.1
    #   env: MOODLE_BRANCH=MOODLE_35_STABLE DB=mariadb
    #   addons:
    #     mariadb: 10.2
    # - php: 7.2
    #   env: MOODLE_BRANCH=MOODLE_36_STABLE DB=mariadb
    #   addons:
    #     mariadb: 10.2
    # - php: 7.3
    #   env: MOODLE_BRANCH=MOODLE_37_STABLE DB=mariadb
    #   addons:
    #     mariadb: 10.2

before_install:
  # php settings
  - echo "upload_max_filesize=20M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo "post_max_size=20M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  # moodle-plugin-ci installation (https://github.com/blackboard-open-source/moodle-plugin-ci/blob/master/.travis.dist.yml)
  - phpenv config-rm xdebug.ini
  - nvm install 14.2.0
  - nvm use 14.2.0
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"
  # chromedriver
  #- chromedriverversion=$(curl https://chromedriver.storage.googleapis.com/LATEST_RELEASE);
  #- curl https://chromedriver.storage.googleapis.com/$chromedriverversion/chromedriver_linux64.zip | gunzip - > ci/bin/chromedriver
  #- chmod +x ci/bin/chromedriver

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache || true # Report errors but don't fail the build (known random failures not able to test the files)
  - moodle-plugin-ci grunt || true # Report errors but don't fail the build (different javascript amd minify files between Moodle < 38 and >= 38)
  - moodle-plugin-ci phpdoc || true # Report errors but don't fail the build (contain incorrect programmer commments and must be fixed some time)
  - moodle-plugin-ci phpunit --coverage-text
  - moodle-plugin-ci behat $( [ "$PROFILE" == "firefox" ] || echo "--profile $PROFILE" )
